import { Entity, Column, PrimaryColumn } from 'typeorm';

@Entity({ schema: 'sepidejam_sepidejam_sg3', name: 'DeliveryNotice' })
export class LegacyDeliveryNotice {
  @PrimaryColumn({ type: 'bigint', name: 'DeliveryNoticeID' })
  deliveryNoticeID: number;

  @Column({ type: 'character varying', name: 'Number' })
  number: string;

  @Column({ type: 'timestamp without time zone', name: 'IssueDate' })
  issueDate: Date;

  @Column({ type: 'timestamp without time zone', name: 'DeliveryDate' })
  deliveryDate: Date;

  @Column({ type: 'integer', name: 'State' })
  state: number;

  @Column({ type: 'bigint', name: 'SupplierRef' })
  supplierRef: number;

  @Column({ type: 'character varying', name: 'Transporter', nullable: true })
  transporter: string | null;

  @Column({ type: 'character varying', name: 'VehicleType', nullable: true })
  vehicleType: string | null;

  @Column({ type: 'character varying', name: 'PlateIdentifier', nullable: true })
  plateIdentifier: string | null;

  @Column({ type: 'character varying', name: 'TransportDocumentNumber', nullable: true })
  transportDocumentNumber: string | null;

  @Column({ type: 'character varying', name: 'SupplierReferenceCode', nullable: true })
  supplierReferenceCode: string | null;

  @Column({ type: 'character varying', name: 'IssuerName', nullable: true })
  issuerName: string | null;

  @Column({ type: 'bigint', name: 'MaintenanceCenterRef', nullable: true })
  maintenanceCenterRef: number | null;

  @Column({ type: 'character varying', name: 'SupplierDescription', nullable: true })
  supplierDescription: string | null;

  @Column({ type: 'character varying', name: 'TraceID', nullable: true })
  traceID: string | null;

  @Column({ type: 'boolean', name: 'AttachmentsReceived', nullable: true })
  attachmentsReceived: boolean | null;

  @Column({ type: 'boolean', name: 'AutoGenerated' })
  autoGenerated: boolean;

  @Column({ type: 'bigint', name: 'Creator' })
  creator: number;

  @Column({ type: 'timestamp without time zone', name: 'CreationDate' })
  creationDate: Date;

  @Column({ type: 'bigint', name: 'LastModifier' })
  lastModifier: number;

  @Column({ type: 'timestamp without time zone', name: 'LastModificationDate' })
  lastModificationDate: Date;

  @Column({ type: 'bytea', name: 'Version' })
  version: Buffer;

}